=== cqframework/healthedecisions/tooling/framework/HeDEngine/Maps/HandlerMap.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by Bryn Rhodes (Veracity Solutions) -->
<!--
	HeD Schema Framework
	Copyright (c) 2012 - 2013 Office of the National Coordinator for Health Information Technology (ONC)
	This file is licensed under a modified BSD-license which can be found in the HED_License.txt file included with this distribution.
-->
<!-- 
	Handler maps are used within the HeD Schema Framework to provide integration points for implementing and extending functionality.
	This schema defines the basic structure of a handler map, as well as the types of handlers that are defined within the framework.
	For each type of handler, an associated interface is defined within the framework to enable implementation of that functionality type.
	For example, the Verification handler map defines classes that are expected to implement the INodeVerifier interface to provide semantic
	verification for the various types of nodes within an HeD Artifact.
-->
<xs:schema xmlns="urn:hl7-org:knowledgeartifact:r1:engine" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:hl7-org:knowledgeartifact:r1:engine" elementFormDefault="qualified" id="HandlerMap">
	<xs:complexType name="Entry">
		<xs:attribute name="key" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Map">
		<xs:sequence>
			<xs:element name="entry" type="Entry" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="handlerType" type="HandlerType"/>
	</xs:complexType>
	<xs:simpleType name="HandlerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ModuleRegistration"/>
			<xs:enumeration value="TypeResolution"/>
			<xs:enumeration value="LibraryReader"/>
			<xs:enumeration value="Verification"/>
			<xs:enumeration value="Evaluation"/>
			<xs:enumeration value="Translation"/>
			<xs:enumeration value="NodeTranslation"/>
			<xs:enumeration value="ModelTranslation"/>
			<xs:enumeration value="Writing"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="map" type="Map"/>
</xs:schema>

=== cqframework/healthedecisions/tooling/framework/HeDEngine/Maps/TypeHandlerMap.xml
<?xml version="1.0" encoding="utf-8" ?> 
<map xmlns="urn:hl7-org:knowledgeartifact:r1:engine" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:knowledgeartifact:r1:engine HandlerMap.xsd" handlerType="TypeResolution">
	<entry key="DateGranularity" value="HeD.Engine.Verification.ScalarTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema-instance:boolean" value="HeD.Engine.Verification.BooleanTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema-instance:int" value="HeD.Engine.Verification.IntegerTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema-instance:string" value="HeD.Engine.Verification.StringTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema-instance:float" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema-instance:double" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema-instance:decimal" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema-instance:dateTime" value="HeD.Engine.Verification.TimestampTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema:boolean" value="HeD.Engine.Verification.BooleanTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema:int" value="HeD.Engine.Verification.IntegerTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema:string" value="HeD.Engine.Verification.StringTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema:float" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema:double" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema:decimal" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="http://www.w3.org/2001/XMLSchema:dateTime" value="HeD.Engine.Verification.TimestampTypeResolver"/>
	<!--entry key="http://www.w3.org/2001/XMLSchema-instance:anyURI" value="HeD.Engine.Verification.UrlTypeResolver"/-->
	<!-- Namespace level model type resolver for all HeD data types. -->
	<entry key="urn:hl7-org:cdsdt:r2" value="HeD.Model.HeDModelTypeResolver"/>
	<!-- Specific type overrides for primitive types in the HeD namespace -->
	<entry key="urn:hl7-org:cdsdt:r2:CD" value="HeD.Engine.Verification.CodeTypeResolver"/>
	<entry key="urn:hl7-org:cdsdt:r2:BL" value="HeD.Engine.Verification.BooleanTypeResolver"/>
	<entry key="urn:hl7-org:cdsdt:r2:INT" value="HeD.Engine.Verification.IntegerTypeResolver"/>
	<entry key="urn:hl7-org:cdsdt:r2:REAL" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="urn:hl7-org:cdsdt:r2:ST" value="HeD.Engine.Verification.StringTypeResolver"/>
	<entry key="urn:hl7-org:cdsdt:r2:TS" value="HeD.Engine.Verification.TimestampTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:Boolean" value="HeD.Engine.Verification.BooleanTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:Integer" value="HeD.Engine.Verification.IntegerTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:Decimal" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:String" value="HeD.Engine.Verification.StringTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:DateTime" value="HeD.Engine.Verification.TimestampTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:Time" value="HeD.Engine.Verification.TimeTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:Quantity" value="HeD.Engine.Verification.PhysicalQuantityTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:Code" value="HeD.Engine.Verification.CodeTypeResolver"/>
	<entry key="urn:hl7-org:elm-types:r1:Concept" value="HeD.Engine.Verification.ConceptTypeResolver"/>
	<entry key="Boolean" value="HeD.Engine.Verification.BooleanTypeResolver"/>
	<entry key="Code" value="HeD.Engine.Verification.CodeTypeResolver"/>
	<entry key="CodedOrdinal" value="HeD.Engine.Verification.CodedOrdinalTypeResolver"/>
	<entry key="EntityName" value="HeD.Engine.Verification.EntityNameTypeResolver"/>
	<entry key="Identifier" value="HeD.Engine.Verification.IdentifierTypeResolver"/>
	<entry key="Integer" value="HeD.Engine.Verification.IntegerTypeResolver"/>
	<entry key="IntegerInterval" value="HeD.Engine.Verification.IntegerIntervalTypeResolver"/>
	<entry key="Period" value="HeD.Engine.Verification.PeriodTypeResolver"/>
	<entry key="PhysicalQuantity" value="HeD.Engine.Verification.PhysicalQuantityTypeResolver"/>
	<entry key="PhysicalQuantityInterval" value="HeD.Engine.Verification.PhysicalQuantityIntervalTypeResolver"/>
	<entry key="QuantityInterval" value="HeD.Engine.Verification.QuantityIntervalTypeResolver"/>
	<entry key="Ratio" value="HeD.Engine.Verification.RatioTypeResolver"/>
	<entry key="Real" value="HeD.Engine.Verification.RealTypeResolver"/>
	<entry key="RealInterval" value="HeD.Engine.Verification.RealIntervalTypeResolver"/>
	<entry key="String" value="HeD.Engine.Verification.StringTypeResolver"/>
	<entry key="Timestamp" value="HeD.Engine.Verification.TimestampTypeResolver"/>
	<entry key="TimestampInterval" value="HeD.Engine.Verification.TimestampIntervalTypeResolver"/>
	<entry key="URL" value="HeD.Engine.Verification.URLTypeResolver"/>
	<!-- Namespace-level model type resolver for the vMR -->
	<!-- TODO: Should be in the vMR.Model Assembly Maps -->
	<entry key="org.opencds.vmr.v1_0.schema.vmr" value="vMR.Model.vMRModelTypeResolver,vMR.Model"/>
	<entry key="urn:hl7-org:vmr:r2" value="vMR.Model.vMRModelTypeResolver,vMR.Model"/>
	<!-- TODO: Should be in the FHIR.Model Assembly Maps -->
	<entry key="http://hl7.org/fhir" value="FHIR.Model.FHIRModelTypeResolver,FHIR.Model"/>
</map>

=== cqframework/healthedecisions/tooling/framework/CREF.Translation/Maps/ModelTranslationHandlerMap.xml
<?xml version="1.0" encoding="utf-8" ?> 
<map xmlns="urn:hl7-org:knowledgeartifact:r1:engine" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:knowledgeartifact:r1:engine ..\..\HeDEngine\Maps\HandlerMap.xsd" handlerType="ModelTranslation">
	<!-- Model transformation classes for CREF Artifacts -->
	<entry key="EvaluatedPerson" value="CREF.Translation.PatientTranslator,CREF.Translation"/>
    <entry key="AD" value="CREF.Translation.AddressTranslator,CREF.Translation"/>
	<entry key="ADXP" value="CREF.Translation.AddressPartTranslator,CREF.Translation"/>
	<entry key="AdverseEvent" value="CREF.Translation.AllergyTranslator,CREF.Translation"/>
	<entry key="DeniedAdverseEvent" value="CREF.Translation.AllergyTranslator,CREF.Translation"/>
	<entry key="EncounterEvent" value="CREF.Translation.EncounterTranslator,CREF.Translation"/>
	<entry key="ObservationOrder" value="CREF.Translation.ResultTranslator,CREF.Translation"/>
	<entry key="ObservationProposal" value="CREF.Translation.ResultTranslator,CREF.Translation"/>
	<entry key="ObservationResult" value="CREF.Translation.ResultTranslator,CREF.Translation"/>
	<entry key="UnconductedObservation" value="CREF.Translation.ResultTranslator,CREF.Translation"/>
	<entry key="Problem" value="CREF.Translation.ProblemTranslator,CREF.Translation"/>
	<entry key="DeniedProblem" value="CREF.Translation.ProblemTranslator,CREF.Translation"/>
	<entry key="ProcedureEvent" value="CREF.Translation.ProcedureTranslator,CREF.Translation"/>
	<entry key="ProcedureOrder" value="CREF.Translation.ProcedureTranslator,CREF.Translation"/>
	<entry key="ProcedureProposal" value="CREF.Translation.ProcedureTranslator,CREF.Translation"/>
	<entry key="SubstanceAdministrationEvent" value="CREF.Translation.MedicationTranslator,CREF.Translation"/>
	<entry key="SubstanceAdministrationOrder" value="CREF.Translation.MedicationTranslator,CREF.Translation"/>
	<entry key="SubstanceAdministrationProposal" value="CREF.Translation.MedicationTranslator,CREF.Translation"/>
	<entry key="UndeliveredSubstanceAdministration" value="CREF.Translation.MedicationTranslator,CREF.Translation"/>
    <entry key="RelatedClinicalStatement" value="CREF.Translation.RelatedClinicalStatementTranslator,CREF.Translation"/>
</map>

=== cqframework/healthedecisions/tooling/framework/SQL.Translation/Maps/ModelTranslationHandlerMap.xml
<?xml version="1.0" encoding="utf-8" ?> 
<map xmlns="urn:hl7-org:knowledgeartifact:r1:engine" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:knowledgeartifact:r1:engine ..\..\HeDEngine\Maps\HandlerMap.xsd" handlerType="ModelTranslation">
	<!-- Model transformation classes for SQL Artifacts -->
	<entry key="EvaluatedPerson" value="SQL.Translation.PatientTranslator,SQL.Translation"/>
    <entry key="AD" value="SQL.Translation.AddressTranslator,SQL.Translation"/>
	<entry key="ADXP" value="SQL.Translation.AddressPartTranslator,SQL.Translation"/>
	<entry key="AdverseEvent" value="SQL.Translation.AllergyTranslator,SQL.Translation"/>
	<entry key="DeniedAdverseEvent" value="SQL.Translation.AllergyTranslator,SQL.Translation"/>
	<entry key="EncounterEvent" value="SQL.Translation.EncounterTranslator,SQL.Translation"/>
	<entry key="ObservationOrder" value="SQL.Translation.ResultTranslator,SQL.Translation"/>
	<entry key="ObservationProposal" value="SQL.Translation.ResultTranslator,SQL.Translation"/>
	<entry key="ObservationResult" value="SQL.Translation.ResultTranslator,SQL.Translation"/>
	<entry key="UnconductedObservation" value="SQL.Translation.ResultTranslator,SQL.Translation"/>
	<entry key="Problem" value="SQL.Translation.ProblemTranslator,SQL.Translation"/>
	<entry key="DeniedProblem" value="SQL.Translation.ProblemTranslator,SQL.Translation"/>
	<entry key="ProcedureEvent" value="SQL.Translation.ProcedureTranslator,SQL.Translation"/>
	<entry key="ProcedureOrder" value="SQL.Translation.ProcedureTranslator,SQL.Translation"/>
	<entry key="ProcedureProposal" value="SQL.Translation.ProcedureTranslator,SQL.Translation"/>
	<entry key="SubstanceAdministrationEvent" value="SQL.Translation.MedicationTranslator,SQL.Translation"/>
	<entry key="SubstanceAdministrationOrder" value="SQL.Translation.MedicationTranslator,SQL.Translation"/>
	<entry key="SubstanceAdministrationProposal" value="SQL.Translation.MedicationTranslator,SQL.Translation"/>
	<entry key="UndeliveredSubstanceAdministration" value="SQL.Translation.MedicationTranslator,SQL.Translation"/>
    <entry key="RelatedClinicalStatement" value="SQL.Translation.RelatedClinicalStatementTranslator,SQL.Translation"/>
</map>

=== cqframework/healthedecisions/tooling/framework/CREF.Translation/Maps/NodeTranslationHandlerMap.xml
<?xml version="1.0" encoding="utf-8" ?> 
<map xmlns="urn:hl7-org:knowledgeartifact:r1:engine" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:knowledgeartifact:r1:engine ..\..\HeDEngine\Maps\HandlerMap.xsd" handlerType="NodeTranslation">
	<!-- Artifact translator for CREF Artifacts -->
	<entry key="urn:hl7-org:knowledgeartifact:r1:ExpressionRef" value="CREF.Translation.ExpressionRefTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:ParameterRef" value="CREF.Translation.ParameterRefTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Literal" value="CREF.Translation.LiteralTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Interval" value="CREF.Translation.IntervalTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:List" value="CREF.Translation.ListTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:And" value="CREF.Translation.AndTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Or" value="CREF.Translation.OrTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Not" value="CREF.Translation.NotTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Case" value="CREF.Translation.CaseTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Conditional" value="CREF.Translation.ConditionalTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Null" value="CREF.Translation.NullTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:IfNull" value="CREF.Translation.IfNullTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Coalesce" value="CREF.Translation.CoalesceTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:As" value="CREF.Translation.AsTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Equal" value="CREF.Translation.EqualTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:NotEqual" value="CREF.Translation.NotEqualTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Less" value="CREF.Translation.LessTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:LessOrEqual" value="CREF.Translation.LessOrEqualTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Greater" value="CREF.Translation.GreaterTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:GreaterOrEqual" value="CREF.Translation.GreaterOrEqualTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Add" value="CREF.Translation.AddTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Divide" value="CREF.Translation.LessTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:TruncatedDivide" value="CREF.Translation.TruncatedDivideTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Modulo" value="CREF.Translation.LessTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Ceiling" value="CREF.Translation.LessTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Floor" value="CREF.Translation.LessTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Negate" value="CREF.Translation.NegateTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Round" value="CREF.Translation.RoundTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Power" value="CREF.Translation.PowerTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:First" value="CREF.Translation.FirstTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Last" value="CREF.Translation.LastTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:DateAdd" value="CREF.Translation.DateAddTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Today" value="CREF.Translation.TodayTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Contains" value="CREF.Translation.ContainsTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:IsEmpty" value="CREF.Translation.IsEmptyTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:IsNotEmpty" value="CREF.Translation.IsNotEmptyTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Filter" value="CREF.Translation.FilterTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:In" value="CREF.Translation.InTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:Property" value="CREF.Translation.PropertyTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:BooleanLiteral" value="CREF.Translation.BooleanLiteralTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:CodeLiteral" value="CREF.Translation.CodeLiteralTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:PhysicalQuantityLiteral" value="CREF.Translation.PhysicalQuantityLiteralTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:StringLiteral" value="CREF.Translation.StringLiteralTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:ClinicalRequest" value="CREF.Translation.ClinicalRequestTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:ValueSet" value="CREF.Translation.ValueSetTranslator,CREF.Translation"/>
	<entry key="urn:hl7-org:knowledgeartifact:r1:InValueSet" value="CREF.Translation.InValueSetTranslator,CREF.Translation"/>
</map>
